import type { NextPage } from "next";
import Head from "next/head";
import { signIn, signOut, useSession } from "next-auth/react";
import Messages from "../components/messages";
import PostMessage from "../components/postMessage";
import EditMessage from "../components/editMessage";
import { useState } from "react";

const Home: NextPage = (props) => {
  const { data: session, status } = useSession();
  const [messageId, setMessageId] = useState("");
  if (status === "loading") {
    return (
      <main>
        <p>...Loading</p>
      </main>
    );
  }
  return (
    <>
      <Head>
        <title>GuestBook App!</title>
        <meta name="Guest Book App" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex flex-col items-center pt-4 m-auto w-[500px] md:w-auto  ">
        {session ? (
          <div className="py-10">
            <div className="flex flex-col items-center">
              <p className="py-5 items-center">
                Well hello there{" "}
                <span className="text-violet-300">{session.user?.name}</span>,
                nice to see you!
              </p>
              <button
                className="bg-violet-900  hover:bg-violet-800 font-bold py-2 px-4 rounded-full "
                onClick={() => signOut()}
              >
                Logout
              </button>
            </div>
            {session.user?.name && messageId ? (
              <div>
                <EditMessage
                  setMessageId={setMessageId}
                  messageId={messageId}
                />
              </div>
            ) : null}

            <div className="pt-16">
              <PostMessage />
            </div>
            <div className="pt-12">
              <Messages setMessageId={setMessageId} />
            </div>
          </div>
        ) : (
          <div className="pt-5">
            <button
              className="bg-violet-900  hover:bg-violet-800 hover:bg-violet-900 font-bold py-2 px-4 rounded-full"
              onClick={() => signIn("discord")}
            >
              Sign In
            </button>
          </div>
        )}
      </main>
    </>
  );
};

export default Home;
