import type { NextPage } from "next";
import Head from "next/head";
import { signIn, signOut, useSession } from "next-auth/react";
import Messages from "../components/messages";
import PostMessage from "../components/postMessage";

const Home: NextPage = (props) => {
  const { data: session, status } = useSession();
  console.log(props);
  if (status === "loading") {
    return (
      <main>
        <p>...Loading</p>
      </main>
    );
  }
  return (
    <>
      <Head>
        <title>Ryan's GuestBook App!</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex flex-col items-center pt-4">
        <h1 className="text-3xl pt-4">Guest Book</h1>
        <p>
          Created with <code>create-t3-app</code>
        </p>

        {session ? (
          <div className="pt-10">
            <p>Hello there {session.user?.name}</p>

            <button onClick={() => signOut()}>Logout</button>
            <div>
              <Messages />
            </div>
            <div className="pt-8">
              <PostMessage />
            </div>
          </div>
        ) : (
          <div>
            <button onClick={() => signIn("discord")}>Sign In</button>
          </div>
        )}
      </main>
    </>
  );
};

export default Home;
